# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\"/\n\nIndividual\x12\x10\n\x08genotype\x18\x01 \x01(\x0c\x12\x0f\n\x07\x66itness\x18\x02 \x01(\x02\"P\n\nPopulation\x12\x1c\n\x07members\x18\x01 \x03(\x0b\x32\x0b.Individual\x12\x16\n\tproblemID\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_problemID\"]\n\x11ImageStreamObject\x12\"\n\x07\x64\x65tails\x18\x01 \x01(\x0b\x32\x0f.ProblemDetailsH\x00\x12\x1c\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x0b.ImageChunkH\x00\x42\x06\n\x04\x64\x61ta\"n\n\x0eProblemDetails\x12\x11\n\tproblemID\x18\x01 \x01(\t\x12\x16\n\x0eimageSizeBytes\x18\x02 \x01(\x05\x12\x1a\n\x12migrationFrequency\x18\x03 \x01(\x05\x12\x15\n\rmigrationSize\x18\x04 \x01(\x05\"\x1a\n\nImageChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x42\x1eZ\x1cvolpe-framework/comms/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034volpe-framework/comms/common'
  _globals['_INDIVIDUAL']._serialized_start=16
  _globals['_INDIVIDUAL']._serialized_end=63
  _globals['_POPULATION']._serialized_start=65
  _globals['_POPULATION']._serialized_end=145
  _globals['_IMAGESTREAMOBJECT']._serialized_start=147
  _globals['_IMAGESTREAMOBJECT']._serialized_end=240
  _globals['_PROBLEMDETAILS']._serialized_start=242
  _globals['_PROBLEMDETAILS']._serialized_end=352
  _globals['_IMAGECHUNK']._serialized_start=354
  _globals['_IMAGECHUNK']._serialized_end=380
# @@protoc_insertion_point(module_scope)
