# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: volpe_container.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'volpe_container.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15volpe_container.proto\x1a\x0c\x63ommon.proto\";\n\x10ResultIndividual\x12\x16\n\x0erepresentation\x18\x01 \x01(\t\x12\x0f\n\x07\x66itness\x18\x02 \x01(\x02\"6\n\x10ResultPopulation\x12\"\n\x07members\x18\x01 \x03(\x0b\x32\x11.ResultIndividual\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x14\n\x04Seed\x12\x0c\n\x04seed\x18\x01 \x01(\x05\"\x1e\n\x0ePopulationSize\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x05Reply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x85\x03\n\x0eVolpeContainer\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x1f\n\x0cInitFromSeed\x12\x05.Seed\x1a\x06.Reply\"\x00\x12/\n\x16InitFromSeedPopulation\x12\x0b.Population\x1a\x06.Reply\"\x00\x12\x33\n\x11GetBestPopulation\x12\x0f.PopulationSize\x1a\x0b.Population\"\x00\x12+\n\tGetRandom\x12\x0f.PopulationSize\x1a\x0b.Population\"\x00\x12\x32\n\nGetResults\x12\x0f.PopulationSize\x1a\x11.ResultPopulation\"\x00\x12\x31\n\x14\x41\x64justPopulationSize\x12\x0f.PopulationSize\x1a\x06.Reply\"\x00\x12.\n\x11RunForGenerations\x12\x0f.PopulationSize\x1a\x06.Reply\"\x00\x42\x13Z\x11./comms/containerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'volpe_container_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021./comms/container'
  _globals['_RESULTINDIVIDUAL']._serialized_start=39
  _globals['_RESULTINDIVIDUAL']._serialized_end=98
  _globals['_RESULTPOPULATION']._serialized_start=100
  _globals['_RESULTPOPULATION']._serialized_end=154
  _globals['_HELLOREQUEST']._serialized_start=156
  _globals['_HELLOREQUEST']._serialized_end=184
  _globals['_SEED']._serialized_start=186
  _globals['_SEED']._serialized_end=206
  _globals['_POPULATIONSIZE']._serialized_start=208
  _globals['_POPULATIONSIZE']._serialized_end=238
  _globals['_HELLOREPLY']._serialized_start=240
  _globals['_HELLOREPLY']._serialized_end=269
  _globals['_REPLY']._serialized_start=271
  _globals['_REPLY']._serialized_end=312
  _globals['_VOLPECONTAINER']._serialized_start=315
  _globals['_VOLPECONTAINER']._serialized_end=704
# @@protoc_insertion_point(module_scope)
